spring.application.name=Chirp

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${CHIRP_DB_URL}
spring.datasource.username=${CHIRP_DB_USERNAME}
spring.datasource.password=${CHIRP_DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
